version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: 'booktracker'
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
